export enum PcErrorCode {
  FACE_POSITION_INVALID = "FACE_POSITION_INVALID",
  FACE_POSITION_TOO_SMALL = "FACE_POSITION_TOO_SMALL",
  FACE_ANGLE_INVALID = "FACE_ANGLE_INVALID",
  LARGE_FACE_ANGLE = "LARGE_FACE_ANGLE",
  NO_FACE = "NO_FACE",
  NO_SHOULDER = "NO_SHOULDER",
  MULTIPLE_PEOPLE = "MULTIPLE_PEOPLE",
  NSFW_DETECTED = "NSFW_DETECTED",
  CREDIT_INSUFFICIENCY = "CREDIT_INSUFFICIENCY",
  EXCEED_MAX_FILESIZE = "EXCEED_MAX_FILESIZE",
  INVALID_API_KEY = "INVALID_API_KEY",
  TASK_TIMEOUT = "TASK_TIMEOUT"
}
