/** IDs generated by CharacterForge blob/local preview storage — not valid on Perfect Corp. */
const LOCAL_PROXY_FILE_ID_PATTERN =
  /^file_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isLocalProxyFileId(fileId: string) {
  return LOCAL_PROXY_FILE_ID_PATTERN.test(fileId);
}
